name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  checks:
    runs-on: ubuntu-latest
    container: golang:1.26.6

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: scripts/pre-commit.sh
      run: ./scripts/pre-commit.sh

    - name: Upload coverage
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: coverage.txt
        if-no-files-found: ignore
